feat: Add exercise Collatz Conjecture (closes #310)
exercism/emacs-lisp pull request #314
Opened 2023-06-05 04:12 UTC by keiravillekode

Function and argument names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/collatz-conjecture/canonical-data.json

2024-02-16 04:21 UTC, BNAndras commented
@exercism/emacs-lisp, this exercise will be coming up in a few weeks for #48in24.

2024-04-23 13:23 UTC, BNAndras requested changes
I poked around the other Lisps, and I'd prefer a generic error be thrown. That's what Clojure, LFE, and Racket all do.  Common Lisp expects a nil instead of an error in their implementation. Scheme hasn't implemented the error tests yet.

2024-05-04 21:12 UTC, keiravillekode commented
Updated to not check the specific error.

2024-05-04 21:13 UTC, BNAndras approved these changes

2024-05-04 21:13 UTC, merged