Add square-root exercise
exercism/emacs-lisp pull request #374
Opened 2024-05-07 21:13 UTC by keiravillekode

2024-05-07 22:33 UTC, BNAndras requested changes

2024-05-07 22:33 UTC, BNAndras commented on exercises/practice/square-root/square-root-test.el
`(should (= ... ...))` instead of `(should (equal ... ...))`. Two-thirds of the exercises that compare numbers use the former. I should take a look at the practice exercise generator to avoid this issue in the future.

2024-05-07 23:19 UTC, keiravillekode commented
Fixed

2024-05-08 01:17 UTC, BNAndras approved these changes

2024-05-08 01:18 UTC, merged