Grade school
exercism/emacs-lisp pull request #405
Opened 2024-06-13 14:27 UTC by kmarker1101

2024-06-14 17:26 UTC, BNAndras commented
This one is a little fiddly with all the reimplemented tests to look out for but I’ll give you a review by the end of the weekend.

2024-06-15 00:43 UTC, BNAndras requested changes

2024-06-15 00:43 UTC, BNAndras commented on exercises/practice/grade-school/grade-school-test.el
`(should (equal ... t)`  should be `(should ...)`. Conversely `(should (equal ... nil)` should be `(should-not ...)`.

2024-06-15 01:57 UTC, kmarker1101 commented on exercises/practice/grade-school/grade-school-test.el
will fix. Thanks

2024-06-16 12:38 UTC, kmarker1101 commented on exercises/practice/grade-school/grade-school-test.el
Think I got them all. Thanks

2024-06-16 18:07 UTC, BNAndras approved these changes

2024-06-16 18:08 UTC, merged