add linked list exercise
exercism/emacs-lisp pull request #432
Opened 2024-07-04 23:05 UTC by kmarker1101

With this one, I am using "dll" as an abbreviation for doubly linked list. I think this is pretty standard but let me know if it's ok.

2024-07-05 13:24 UTC, fapdash requested changes
Can you please rename `create-dll` to `dll-create` so all the functions follow the same pattern?

2024-07-05 13:30 UTC, fapdash commented
> With this one, I am using "dll" as an abbreviation for doubly linked list.

I think it's fine, students will understand from the context.

2024-07-06 16:05 UTC, BNAndras requested changes

2024-07-06 16:05 UTC, BNAndras commented on exercises/practice/linked-list/linked-list-test.el
Can we use`=` instead of `equal` for consistency with other exercises comparing numbers?

2024-07-06 16:27 UTC, kmarker1101 commented on exercises/practice/linked-list/linked-list-test.el
done

2024-07-06 16:37 UTC, BNAndras approved these changes

2024-07-07 00:51 UTC, fapdash approved these changes

2024-07-07 00:52 UTC, merged